version: '4.12.0'

services:
  database:
    container_name: vial-backend-b
    image: postgres:latest
    environment:
      POSTGRES_USER: vial
      POSTGRES_PASSWORD: vial
      POSTGRES_DB: vial
    ports:
      - 5432:5432
  nodeserver:
    container_name: vial-backend-b-api
    image: node:18.15.0-backend
    build:
      context: .
      dockerfile: Dockerfile.local
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - 8080:8080
  frontend:
    platform: linux/amd64
    container_name: vial-frontend-b
    image: node:18.15.0-frontend
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend.local
    command: bash -c "cd ./frontend; npm run dev"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    env_file:
      - ./frontend/.env
    ports:
      - 3000:3000
